import type { OfferProject } from "./offer-schema";

export function offerToMarkdown({ brief, offer }: OfferProject): string {
  const lines: string[] = [];
  const push = (value: string) => lines.push(value);

  push(`# ${offer.productName}`);
  push(`_${offer.slogan}_`);
  push("");
  push(`**Nicho:** ${brief.nicho} · **Formato:** ${brief.formato} · **Preço:** ${brief.preco}`);
  push(`**Objetivo:** ${brief.objetivo}`);
  push("");
  push("## Promessa");
  push(offer.bigPromise);
  push("");
  push("## Posicionamento");
  push(offer.positioning);
  push(`Tom de voz: ${offer.toneOfVoice}`);
  push(`Avatar: ${offer.avatar}`);
  push("");
  push("## Copy");
  push(`**Headline:** ${offer.headline}`);
  push(`**Subheadline:** ${offer.subheadline}`);
  push("");
  push("### Bullets");
  offer.bullets.forEach((b) => push(`- ${b}`));
  push("");
  push("### CTAs");
  offer.ctas.forEach((c) => push(`- ${c}`));
  push("");
  push("## Produto");
  offer.productModules.forEach((m) => push(`- **${m.title}** — ${m.description}`));
  push("");
  push("## Bônus");
  offer.bonuses.forEach((b) => push(`- **${b.title}** (${b.perceivedValue}) — ${b.description}`));
  push("");
  push("## Garantia");
  push(`**${offer.guarantee.title}** — ${offer.guarantee.description}`);
  push("");
  push("## Página de vendas");
  push(`Hero: ${offer.landing.heroHeadline}`);
  push(`Sub: ${offer.landing.heroSubheadline}`);
  push(`Dores: ${offer.landing.painSection}`);
  push(`Desejos: ${offer.landing.desireSection}`);
  push(`Transformação: ${offer.landing.transformation}`);
  offer.landing.stack.forEach((s) => push(`- ${s}`));
  push(`CTA final: ${offer.landing.finalCta}`);
  push("");
  push("## Objeções");
  offer.objections.forEach((o) => push(`- **${o.objection}** — ${o.answer}`));
  push("");
  push("## FAQ");
  offer.faq.forEach((f) => push(`- **${f.question}** — ${f.answer}`));
  push("");
  push("## Funil");
  offer.funnel.forEach((f) => push(`- **${f.stage}** — ${f.description}`));
  push("");
  push("## Criativos");
  offer.creatives.forEach((c) => push(`- **${c.format}** — ${c.hook}\n\n${c.script}\n`));
  push("");
  push("## E-mails");
  offer.emails.forEach((e) => push(`- **${e.subject}**\n\n${e.body}\n`));
  push("");
  push("## Pesquisa de mercado");
  push(`Preço médio: ${offer.marketResearch.averagePrice}`);
  offer.marketResearch.trends.forEach((t) => push(`- Tendência: ${t}`));
  offer.marketResearch.opportunities.forEach((o) => push(`- Oportunidade: ${o}`));
  push("");
  push("## Plano de lançamento");
  offer.launchPlan.forEach((s) => push(`- ${s}`));
  push("");
  push(`## Score: ${offer.score.total}/100`);
  offer.score.suggestions.forEach((s) => push(`- ${s}`));

  return lines.join("\n");
}
