/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ConfiguracoesRouteImport } from './routes/configuracoes'
import { Route as CopywriterRouteImport } from './routes/copywriter'
import { Route as NovaOfertaRouteImport } from './routes/nova-oferta'
import { Route as TemplatesRouteImport } from './routes/templates'
import { Route as EmBreveSlugRouteImport } from './routes/em-breve.$slug'
import { Route as OfertasIndexRouteImport } from './routes/ofertas.index'
import { Route as OfertasIdRouteImport } from './routes/ofertas.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ConfiguracoesRoute = ConfiguracoesRouteImport.update({
  id: '/configuracoes',
  path: '/configuracoes',
  getParentRoute: () => rootRouteImport,
} as any)
const CopywriterRoute = CopywriterRouteImport.update({
  id: '/copywriter',
  path: '/copywriter',
  getParentRoute: () => rootRouteImport,
} as any)
const NovaOfertaRoute = NovaOfertaRouteImport.update({
  id: '/nova-oferta',
  path: '/nova-oferta',
  getParentRoute: () => rootRouteImport,
} as any)
const TemplatesRoute = TemplatesRouteImport.update({
  id: '/templates',
  path: '/templates',
  getParentRoute: () => rootRouteImport,
} as any)
const EmBreveSlugRoute = EmBreveSlugRouteImport.update({
  id: '/em-breve/$slug',
  path: '/em-breve/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const OfertasIndexRoute = OfertasIndexRouteImport.update({
  id: '/ofertas/',
  path: '/ofertas/',
  getParentRoute: () => rootRouteImport,
} as any)
const OfertasIdRoute = OfertasIdRouteImport.update({
  id: '/ofertas/$id',
  path: '/ofertas/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/configuracoes': typeof ConfiguracoesRoute
  '/copywriter': typeof CopywriterRoute
  '/nova-oferta': typeof NovaOfertaRoute
  '/templates': typeof TemplatesRoute
  '/em-breve/$slug': typeof EmBreveSlugRoute
  '/ofertas/$id': typeof OfertasIdRoute
  '/ofertas/': typeof OfertasIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/configuracoes': typeof ConfiguracoesRoute
  '/copywriter': typeof CopywriterRoute
  '/nova-oferta': typeof NovaOfertaRoute
  '/templates': typeof TemplatesRoute
  '/em-breve/$slug': typeof EmBreveSlugRoute
  '/ofertas/$id': typeof OfertasIdRoute
  '/ofertas': typeof OfertasIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/configuracoes': typeof ConfiguracoesRoute
  '/copywriter': typeof CopywriterRoute
  '/nova-oferta': typeof NovaOfertaRoute
  '/templates': typeof TemplatesRoute
  '/em-breve/$slug': typeof EmBreveSlugRoute
  '/ofertas/$id': typeof OfertasIdRoute
  '/ofertas/': typeof OfertasIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/configuracoes'
    | '/copywriter'
    | '/nova-oferta'
    | '/templates'
    | '/em-breve/$slug'
    | '/ofertas/$id'
    | '/ofertas/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/configuracoes'
    | '/copywriter'
    | '/nova-oferta'
    | '/templates'
    | '/em-breve/$slug'
    | '/ofertas/$id'
    | '/ofertas'
  id:
    | '__root__'
    | '/'
    | '/configuracoes'
    | '/copywriter'
    | '/nova-oferta'
    | '/templates'
    | '/em-breve/$slug'
    | '/ofertas/$id'
    | '/ofertas/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ConfiguracoesRoute: typeof ConfiguracoesRoute
  CopywriterRoute: typeof CopywriterRoute
  NovaOfertaRoute: typeof NovaOfertaRoute
  TemplatesRoute: typeof TemplatesRoute
  EmBreveSlugRoute: typeof EmBreveSlugRoute
  OfertasIdRoute: typeof OfertasIdRoute
  OfertasIndexRoute: typeof OfertasIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/configuracoes': {
      id: '/configuracoes'
      path: '/configuracoes'
      fullPath: '/configuracoes'
      preLoaderRoute: typeof ConfiguracoesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/copywriter': {
      id: '/copywriter'
      path: '/copywriter'
      fullPath: '/copywriter'
      preLoaderRoute: typeof CopywriterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/nova-oferta': {
      id: '/nova-oferta'
      path: '/nova-oferta'
      fullPath: '/nova-oferta'
      preLoaderRoute: typeof NovaOfertaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/templates': {
      id: '/templates'
      path: '/templates'
      fullPath: '/templates'
      preLoaderRoute: typeof TemplatesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/em-breve/$slug': {
      id: '/em-breve/$slug'
      path: '/em-breve/$slug'
      fullPath: '/em-breve/$slug'
      preLoaderRoute: typeof EmBreveSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ofertas/': {
      id: '/ofertas/'
      path: '/ofertas'
      fullPath: '/ofertas/'
      preLoaderRoute: typeof OfertasIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ofertas/$id': {
      id: '/ofertas/$id'
      path: '/ofertas/$id'
      fullPath: '/ofertas/$id'
      preLoaderRoute: typeof OfertasIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ConfiguracoesRoute: ConfiguracoesRoute,
  CopywriterRoute: CopywriterRoute,
  NovaOfertaRoute: NovaOfertaRoute,
  TemplatesRoute: TemplatesRoute,
  EmBreveSlugRoute: EmBreveSlugRoute,
  OfertasIdRoute: OfertasIdRoute,
  OfertasIndexRoute: OfertasIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
