/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as CadastroRouteImport } from './routes/cadastro'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AuthenticatedIndexRouteImport } from './routes/_authenticated/index'
import { Route as AuthenticatedConfiguracoesRouteImport } from './routes/_authenticated/configuracoes'
import { Route as AuthenticatedCopywriterRouteImport } from './routes/_authenticated/copywriter'
import { Route as AuthenticatedNovaOfertaRouteImport } from './routes/_authenticated/nova-oferta'
import { Route as AuthenticatedTemplatesRouteImport } from './routes/_authenticated/templates'
import { Route as EmBreveSlugRouteImport } from './routes/em-breve.$slug'
import { Route as AuthenticatedOfertasIndexRouteImport } from './routes/_authenticated/ofertas.index'
import { Route as AuthenticatedOfertasIdRouteImport } from './routes/_authenticated/ofertas.$id'

const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const CadastroRoute = CadastroRouteImport.update({
  id: '/cadastro',
  path: '/cadastro',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedIndexRoute = AuthenticatedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedConfiguracoesRoute =
  AuthenticatedConfiguracoesRouteImport.update({
    id: '/configuracoes',
    path: '/configuracoes',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedCopywriterRoute = AuthenticatedCopywriterRouteImport.update({
  id: '/copywriter',
  path: '/copywriter',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedNovaOfertaRoute = AuthenticatedNovaOfertaRouteImport.update({
  id: '/nova-oferta',
  path: '/nova-oferta',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedTemplatesRoute = AuthenticatedTemplatesRouteImport.update({
  id: '/templates',
  path: '/templates',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const EmBreveSlugRoute = EmBreveSlugRouteImport.update({
  id: '/em-breve/$slug',
  path: '/em-breve/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedOfertasIndexRoute =
  AuthenticatedOfertasIndexRouteImport.update({
    id: '/ofertas/',
    path: '/ofertas/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedOfertasIdRoute = AuthenticatedOfertasIdRouteImport.update({
  id: '/ofertas/$id',
  path: '/ofertas/$id',
  getParentRoute: () => AuthenticatedRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof AuthenticatedIndexRoute
  '/cadastro': typeof CadastroRoute
  '/login': typeof LoginRoute
  '/configuracoes': typeof AuthenticatedConfiguracoesRoute
  '/copywriter': typeof AuthenticatedCopywriterRoute
  '/nova-oferta': typeof AuthenticatedNovaOfertaRoute
  '/templates': typeof AuthenticatedTemplatesRoute
  '/em-breve/$slug': typeof EmBreveSlugRoute
  '/ofertas/$id': typeof AuthenticatedOfertasIdRoute
  '/ofertas/': typeof AuthenticatedOfertasIndexRoute
}
export interface FileRoutesByTo {
  '/cadastro': typeof CadastroRoute
  '/login': typeof LoginRoute
  '/configuracoes': typeof AuthenticatedConfiguracoesRoute
  '/copywriter': typeof AuthenticatedCopywriterRoute
  '/nova-oferta': typeof AuthenticatedNovaOfertaRoute
  '/templates': typeof AuthenticatedTemplatesRoute
  '/em-breve/$slug': typeof EmBreveSlugRoute
  '/': typeof AuthenticatedIndexRoute
  '/ofertas/$id': typeof AuthenticatedOfertasIdRoute
  '/ofertas': typeof AuthenticatedOfertasIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/cadastro': typeof CadastroRoute
  '/login': typeof LoginRoute
  '/_authenticated/configuracoes': typeof AuthenticatedConfiguracoesRoute
  '/_authenticated/copywriter': typeof AuthenticatedCopywriterRoute
  '/_authenticated/nova-oferta': typeof AuthenticatedNovaOfertaRoute
  '/_authenticated/templates': typeof AuthenticatedTemplatesRoute
  '/em-breve/$slug': typeof EmBreveSlugRoute
  '/_authenticated/': typeof AuthenticatedIndexRoute
  '/_authenticated/ofertas/$id': typeof AuthenticatedOfertasIdRoute
  '/_authenticated/ofertas/': typeof AuthenticatedOfertasIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/cadastro'
    | '/login'
    | '/configuracoes'
    | '/copywriter'
    | '/nova-oferta'
    | '/templates'
    | '/em-breve/$slug'
    | '/ofertas/$id'
    | '/ofertas/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/cadastro'
    | '/login'
    | '/configuracoes'
    | '/copywriter'
    | '/nova-oferta'
    | '/templates'
    | '/em-breve/$slug'
    | '/'
    | '/ofertas/$id'
    | '/ofertas'
  id:
    | '__root__'
    | '/_authenticated'
    | '/cadastro'
    | '/login'
    | '/_authenticated/configuracoes'
    | '/_authenticated/copywriter'
    | '/_authenticated/nova-oferta'
    | '/_authenticated/templates'
    | '/em-breve/$slug'
    | '/_authenticated/'
    | '/_authenticated/ofertas/$id'
    | '/_authenticated/ofertas/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  CadastroRoute: typeof CadastroRoute
  LoginRoute: typeof LoginRoute
  EmBreveSlugRoute: typeof EmBreveSlugRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cadastro': {
      id: '/cadastro'
      path: '/cadastro'
      fullPath: '/cadastro'
      preLoaderRoute: typeof CadastroRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/': {
      id: '/_authenticated/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/configuracoes': {
      id: '/_authenticated/configuracoes'
      path: '/configuracoes'
      fullPath: '/configuracoes'
      preLoaderRoute: typeof AuthenticatedConfiguracoesRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/copywriter': {
      id: '/_authenticated/copywriter'
      path: '/copywriter'
      fullPath: '/copywriter'
      preLoaderRoute: typeof AuthenticatedCopywriterRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/nova-oferta': {
      id: '/_authenticated/nova-oferta'
      path: '/nova-oferta'
      fullPath: '/nova-oferta'
      preLoaderRoute: typeof AuthenticatedNovaOfertaRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/templates': {
      id: '/_authenticated/templates'
      path: '/templates'
      fullPath: '/templates'
      preLoaderRoute: typeof AuthenticatedTemplatesRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/em-breve/$slug': {
      id: '/em-breve/$slug'
      path: '/em-breve/$slug'
      fullPath: '/em-breve/$slug'
      preLoaderRoute: typeof EmBreveSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/ofertas/': {
      id: '/_authenticated/ofertas/'
      path: '/ofertas'
      fullPath: '/ofertas/'
      preLoaderRoute: typeof AuthenticatedOfertasIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/ofertas/$id': {
      id: '/_authenticated/ofertas/$id'
      path: '/ofertas/$id'
      fullPath: '/ofertas/$id'
      preLoaderRoute: typeof AuthenticatedOfertasIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
  }
}

interface AuthenticatedRouteChildren {
  AuthenticatedConfiguracoesRoute: typeof AuthenticatedConfiguracoesRoute
  AuthenticatedCopywriterRoute: typeof AuthenticatedCopywriterRoute
  AuthenticatedNovaOfertaRoute: typeof AuthenticatedNovaOfertaRoute
  AuthenticatedTemplatesRoute: typeof AuthenticatedTemplatesRoute
  AuthenticatedIndexRoute: typeof AuthenticatedIndexRoute
  AuthenticatedOfertasIdRoute: typeof AuthenticatedOfertasIdRoute
  AuthenticatedOfertasIndexRoute: typeof AuthenticatedOfertasIndexRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedConfiguracoesRoute: AuthenticatedConfiguracoesRoute,
  AuthenticatedCopywriterRoute: AuthenticatedCopywriterRoute,
  AuthenticatedNovaOfertaRoute: AuthenticatedNovaOfertaRoute,
  AuthenticatedTemplatesRoute: AuthenticatedTemplatesRoute,
  AuthenticatedIndexRoute: AuthenticatedIndexRoute,
  AuthenticatedOfertasIdRoute: AuthenticatedOfertasIdRoute,
  AuthenticatedOfertasIndexRoute: AuthenticatedOfertasIndexRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  CadastroRoute: CadastroRoute,
  LoginRoute: LoginRoute,
  EmBreveSlugRoute: EmBreveSlugRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
